### PR TITLE
Python3 version

### PR DESCRIPTION
**Pull request by Yi666**

### CODE REVIEW

**Review by justinabrahms — APPROVED** [review]
Looks good to me from a code perspective. We should get automated tests running on this repo though.

**Comment by Yi666** [comment]
> Looks good to me from a code perspective. We should get automated tests running on this repo though.

Thanks @justinabrahms, that's a great suggestion, will work on the tests and create another PR for it.

**Comment by dvijayan-ebay** [comment]
@Yi666 can you update the lib version 
https://github.com/eBay/FeedSDK-Python/security/dependabot

**Review by justinabrahms — APPROVED** [review]

**Comment by dvijayan-ebay** [comment]
thanks @Yi666

**Pull request merged**
